### PR TITLE
DEV: add getBucketLocation

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by rahulreddy** [comment]
@nicolas2bert Please go ahead and squash the commits. I will merge the PR once end to end is run.

**Comment by nicolas2bert** [comment]
ok - we don't need to wait for https://github.com/scality/S3/pull/535 to be merged, right?

**Comment by rahulreddy** [comment]
Yes, this can go first given that S3 is not merged yet.

**Comment by nicolas2bert** [comment]
@ironman-machine try

**Comment by nicolas2bert** [comment]
http://ci.ironmann.io/gh/scality/Integration/9332

**Comment by nicolas2bert** [comment]
New E2E: http://ci.ironmann.io/gh/scality/Integration/9733

**Comment by nicolas2bert** [comment]
New E2E - CI fixed - http://ci.ironmann.io/gh/scality/Integration/9798

**Pull request merged**
