### PR TITLE
Refactor: Use generic methods array

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Use a single array for any generic method. Use this array to build necessary object mappings and run associated tests.

This reduces the task of adding a new generic method to Utapi to just updating this array and the S3MetricResponse object.

Note that this also adds a missing test for the 'createBucket' operation in testMetrics.js, hence the additional 4 unit tests (one additional test for each of the four metric levels).

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
Good work! I may have some cosmetic changes here and there.

**Comment by bennettbuchanan** [comment]
I've been wanting to do that for a while 😺

**Review by philipyoo — APPROVED** [review]

**Comment by bennettbuchanan** [comment]
These changes can be added if expanding Utapi metrics going forward.

**Pull request closed without merging**
