### PR TITLE
Improvement/s3 c 2290 upgrade nodejs

### PR DESCRIPTION
**Pull request by Katherinelaue1**
**What does this PR do, and why do we need it?**
Update Utapi node.js to 10.x

**Which issue does this PR fix?**
fixes #S3C-2304

**Special notes for your reviewers:**

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Review by rahulreddy — APPROVED** [review]

**Review by bennettbuchanan — APPROVED** [review]
Thank you for this! 🚢

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Pull request merged**
