### PR TITLE
Update s3_bucketd.py

### PR DESCRIPTION
**Pull request by scality-gelbart**
same as #1030

### CODE REVIEW

**Review by scality-gdoumergue — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Comment by jonathan-gramain** [comment]
@scality-gelbart We may want this fix in 7.9.0, in which case the PR should target `stabilization/7.9.0` instead.

@rahulreddy @terrydervaux is this still doable regarding the delivery timeline?

**Comment by scality-gdoumergue** [comment]
@jonathan-gramain @rahulreddy @terrydervaux I concur with the idea of merging #1030 and #1033 into stabilization/7.9.0. #1036 should be, too.

**Review by tmacro — APPROVED** [review]

**Pull request merged**
