### PR TITLE
FIX: Send correct request object to Arsenal

### PR DESCRIPTION
**Pull request by bennettbuchanan**
* Adds a `query` property for passing to `doAuth`. 
* Uses `url.pathname` for the `path` property sent to Arsenal.

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
E2E running here: http://ci.ironmann.io/gh/scality/Integration/9017#build-parameters

**Comment by bennettbuchanan** [comment]
e2e triggered here with default branch: http://ci.ironmann.io/gh/scality/Integration/9023

**Comment by bennettbuchanan** [comment]
e2e triggered here with default branch against ultron/rel/6.3: http://ci.ironmann.io/gh/scality/Integration/9037

**Comment by bennettbuchanan** [comment]
e2e after rebase: http://ci.ironmann.io/gh/scality/Integration/9207

**Comment by bennettbuchanan** [comment]
http://ci.ironmann.io/gh/scality/Integration/9208

**Comment by bennettbuchanan** [comment]
e2e after new methods are added: http://ci.ironmann.io/gh/scality/Integration/9212

**Comment by alexandre-merle** [comment]
Sending the query parameters with the post parameters for a POST request seem to not work at all, resulting in a forbidden Vault side

**Comment by rahulreddy** [comment]
@alexandre-merle The Arsenal method for auth we have expects pathname as input instead of the entire path with query params. So the error would actually be on the calling function to send the appropriate params.
I will be adding a comment for that method in Arsenal explaining so.

**Comment by bennettbuchanan** [comment]
e2e with @rahulreddy's fix in Integration: http://ci.ironmann.io/gh/scality/Integration/9224#build-parameters

**Comment by bennettbuchanan** [comment]
retry: http://ci.ironmann.io/gh/scality/Integration/9235

**Comment by bennettbuchanan** [comment]
rebuild: http://ci.ironmann.io/gh/scality/Integration/9256

**Comment by bennettbuchanan** [comment]
Do not use Ultron: http://ci.ironmann.io/gh/scality/Integration/9261

**Comment by bennettbuchanan** [comment]
e2e passed

**Pull request merged**
