### PR TITLE
FIX: Reuse only the first reqUid in UtapiReplay

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@bennettbuchanan We need to  fix 6.4 and then apply forward ports to the newer releases.

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_BASE_BRANCH=rel/6.4
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
DEFAULT_BRANCH=rel/6.4
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
DEFAULT_BRANCH=rel/6.4
INTEGRATION_BRANCH=rel/6.4
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
DEFAULT_BRANCH=rel/6.4
SCALITY_INTEGRATION_BRANCH=rel/6.4
INTEGRATION_BRANCH=
try

**Comment by bennettbuchanan** [comment]
E2E passed here: http://ci.ironmann.io/gh/scality/Integration/14834#build-parameters

**Pull request merged**
