### PR TITLE
FT: putObjectTagging

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by nicolas2bert** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by nicolas2bert** [comment]
@rahulreddy Can we try one more time? :)

**Comment by rahulreddy** [comment]
Build passed here http://ci.ironmann.io/gh/scality/Integration/12664

**Pull request merged**
