### PR TITLE
FT: Add putBucketReplication metrics

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-put-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-put-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-put-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-put-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-put-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-put-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-put-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-put-bucket-replication
SCALITY_ARSENAL_BRANCH=S3C-291-put-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_INTEGRATION_BRANCH=S3C-291-put-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_INTEGRATION_BRANCH=S3C-291-put-bucket-replication
try

**Comment by rahulreddy** [comment]
@ironman-machine

**Pull request merged**
