### PR TITLE
Update s3_bucketd.py

### PR DESCRIPTION
**Pull request by scality-gelbart**
sorry guys, requesting your review AGAIN, I messed up with git

### CODE REVIEW

**Review by jonathan-gramain — APPROVED** [review]

**Comment by jonathan-gramain** [comment]
@scality-gelbart We may want this fix in 7.9.0, in which case the PR should target `stabilization/7.9.0` instead.

@rahulreddy @terrydervaux is this still doable regarding the delivery timeline?

**Review by scality-gdoumergue — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Pull request merged**
