### PR TITLE
ft(S3C-3524): upgrade warp10 to 2.7.2

### PR DESCRIPTION
**Pull request by tmacro**

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]
Random aside, does dependabot support upgrading base images or some other tool?

**Comment by tmacro** [comment]
not that I'm aware of

**Review by ilkescality — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
@miniscruff I think it could if there is a way to declare our versions as python's requirements.txt or yum or some other standardized way package managers use to manage dependencies.

**Comment by rahulreddy** [comment]
> @miniscruff I think it could if there is a way to declare our versions as python's requirements.txt or yum or some other standardized way package managers use to manage dependencies.

Scratch that, I thought that I was in Federation for a second.
@tmacro You are bumping the version in Federation as well right? This image is used by Utapi project specifically.

**Comment by tmacro** [comment]
@rahulreddy yes

**Pull request merged**
