### PR TITLE
ft(S3C-3351): Cache js dependencies in buildbot worker

### PR DESCRIPTION
**Pull request by tmacro**

### CODE REVIEW

**Review by tcarmet — APPROVED** [review]
:sunglasses:

**Comment by tcarmet** [comment]
Open question, don't you want to merge this in 7.4? or is the code just not the same?

**Review by anurag4DSB — APPROVED** [review]

**Comment by tmacro** [comment]
@tcarmet ~That would make more sense~ On second thought, I'll do a separate PR to backport the changes as it gets a bit messy

**Comment by tcarmet** [comment]
> @tcarmet ~That would make more sense~ On second thought, I'll do a separate PR to backport the changes as it gets a bit messy

alrighty

**Pull request merged**
