### PR TITLE
FT: Add Utapi tracking for CORS api

### PR DESCRIPTION
**Pull request by electrachong**

### CODE REVIEW

**Comment by electrachong** [comment]
@bennettbuchanan thanks, I added some tests and saw some bucket website tests were also missing so added them. Let me know if you want to extract them into another pr or commit.

**Comment by electrachong** [comment]
passes with scality/Integration#434 here: http://ci.ironmann.io/gh/scality/Integration/8976

**Comment by bennettbuchanan** [comment]
Indeed, @electrachong. It's minor but you might add another commit for introducing those missing bucketWebsite tests to keep separation of concerns. Perhaps this can happen when you squash the commits.

**Comment by electrachong** [comment]
@ironman-machine try

**Comment by electrachong** [comment]
running an end-to-end with current rel/6.4 S3 branch here: http://ci.ironmann.io/gh/scality/Integration/9217

**Comment by electrachong** [comment]
latest end-to-end passed

**Pull request merged**
