### PR TITLE
bugfix: Fix permissions on warp10 release workflow

### PR DESCRIPTION
**Pull request by anurag4DSB**
Issue: UTAPI-108

Added permissions for github release workflow.
Sample release: https://github.com/scality/utapi/pkgs/container/utapi%2Fwarp10/274300640?tag=7.10.11-PW.1

### CODE REVIEW

**Comment by anurag4DSB** [comment]
ping

**Review by BourgoisMickael — APPROVED** [review]

**Comment by anurag4DSB** [comment]
added a force push commit where I changed `tag_name: ${{ github.event.inputs.tag }}-warp10` to `tag_name: ${{ inputs.tag }}-warp10`

**Review by fredmnl — APPROVED** [review]

**Pull request merged**
