### PR TITLE
FT: Add getBucketReplication

### PR DESCRIPTION
**Pull request by bennettbuchanan**

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-get-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-get-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@e2e against master passed here: http://ci.ironmann.io/gh/scality/Integration/13372#build-parameters

**Comment by rahulreddy** [comment]
We should automate this for generic push metric as it's the same for every single one.

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-get-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-get-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-get-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-get-bucket-replication
SCALITY_ARSENAL_BRANCH=S3C-291-get-bucket-replication
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-291-get-bucket-replication
SCALITY_INTEGRATION_BRANCH=S3C-291-get-bucket-replication
SCALITY_ARSENAL_BRANCH=S3C-291-get-bucket-replication
try

**Comment by bennettbuchanan** [comment]
Passed E2E.

**Pull request merged**
