### PR TITLE
FT: Separate Utapi from S3

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Do not review—for testing purposes.

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@ironman-machine 
SCALITY_S3_BRANCH=S3C-150/ft-separate-utapi-from-s3
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_S3_BRANCH=S3C-150/ft-separate-utapi-from-s3
try

**Comment by rahulreddy** [comment]
We will target this for GA 7.1

**Comment by bennettbuchanan** [comment]
We can reopen if there is a need to come back to this task.

**Pull request closed without merging**
