### PR TITLE
Feature/s3 c 2960 object lock metrics

### PR DESCRIPTION
**Pull request by dora-korpar**
Adds metrics for 6 new Object Lock related APIs: PUT/GET bucket object lock configuration, PUT/GET object retention, and PUT/GET object legal hold

### CODE REVIEW

**Comment by dora-korpar** [comment]
@bert-e reset

**Comment by dora-korpar** [comment]
@bert-e reset

**Comment by miniscruff** [comment]
Nothing seems wrong here but I feel 103 changes to add 6 metrics is a bit much. Like an automated middleware that provides metrics automatically or as a decorator. Just something to consider.

**Review by miniscruff — APPROVED** [review]

**Review by ilkescality — APPROVED** [review]

**Comment by dora-korpar** [comment]
@miniscruff, something to pitch for the new Utapi implementation :)

**Comment by miniscruff** [comment]
> @miniscruff, something to pitch for the new Utapi implementation :)

Well, it should apply any API we want to publish metrics for, I wouldn't expect UTAPI to be the only one.

**Review by tmacro — APPROVED** [review]

**Comment by tmacro** [comment]
@miniscruff the new design is generic. There's no special handling of individual metric needed, so the only change would be adding the operationId to the enum used to validate a metric

**Comment by miniscruff** [comment]
> @miniscruff the new design is generic. There's no special handling of individual metric needed, so the only change would be adding the operationId to the enum used to validate a metric

oooh that sounds good, well better anyway. Where can I get a preview of this new design? I have been avoiding design PRs as I just don't understand enough to contribute.

**Comment by dora-korpar** [comment]
@bert-e approve

**Pull request merged**
