### PR TITLE
Improvement: S3C-2365 update deps

### PR DESCRIPTION
**Pull request by Katherinelaue1**
**What does this PR do, and why do we need it?**
Update Utapi Vaultclient dependency 

**Which issue does this PR fix?**
fixes #S3C-2365

**Special notes for your reviewers:**

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
@bert-e status

**Review by rahulreddy — APPROVED** [review]

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by Katherinelaue1** [comment]
@bert-e force_reset

**Comment by Katherinelaue1** [comment]
@bert-e status

**Comment by Katherinelaue1** [comment]
@bert-e status

**Comment by Katherinelaue1** [comment]
@bert-e force_reset

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Comment by Katherinelaue1** [comment]
@bert-e status

**Pull request merged**
