### PR TITLE
replace transient state error with explicit info

### PR DESCRIPTION
**Pull request by scality-gelbart**
fixes [S3C-4591](https://scality.atlassian.net/browse/S3C-4591) and [S3C-4975](https://scality.atlassian.net/browse/S3C-4975)

[S3C-4975]: https://scality.atlassian.net/browse/S3C-4975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tmacro** [comment]
we need to remove the test cases that enforce the error we're removing

**Comment by scality-gelbart** [comment]
Hello @tmacro, can you help on removing the test that enforces the error ?

**Comment by tmacro** [comment]
@scality-gelbart I'll pick it up next week

**Review by tmacro — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Pull request merged**
