### PR TITLE
ft(S3C-3418): Change wire format to json for warp10 ingestion

### PR DESCRIPTION
**Pull request by tmacro**
Drop our bespoke packing into warpscript syntax and switch to JSON. I'm choosing this over extending the existing solution as we don't need to maintain any custom code.

### CODE REVIEW

**Review by jonathan-gramain — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Review by ilkescality — APPROVED** [review]
LGTM (noticed some linter failures, but probably minor)

**Pull request merged**
