### PR TITLE
improvement: S3C-2337 Parallelize tests

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Parallelize tests into stages to reduce overall test runtime.

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@bert-e reset

**Comment by bennettbuchanan** [comment]
@bert-e reset

**Comment by bennettbuchanan** [comment]
@bert-e reset

**Review by JianqinWang — APPROVED** [review]

**Review by ssalaues — APPROVED** [review]
Nice

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by bennettbuchanan** [comment]
@bert-e approve

**Pull request merged**
